from gameboard import GameBoard

def solve(b):
    if b.height == 1: #1 move
        b.movepiece(0,2)
    elif b.height == 2: #3 moves
        b.movepiece(0,1)
        b.movepiece(0,2)
        b.movepiece(1,2)
    elif b.height == 3: #7 moves
        b.movepiece(0,2)
        b.movepiece(0,1)
        b.movepiece(2,1)
        b.movepiece(0,2)
        b.movepiece(1,0)
        b.movepiece(1,2)
        b.movepiece(0,2)
    elif b.height == 4: #15 moves
        b.movepiece(0,1)
        b.movepiece(0,2)
        b.movepiece(1,2)
        b.movepiece(0,1)
        b.movepiece(2,0)
        b.movepiece(2,1)
        b.movepiece(0,1)
        b.movepiece(0,2)
        b.movepiece(1,2)
        b.movepiece(1,0)
        b.movepiece(2,0)
        b.movepiece(1,2)
        b.movepiece(0,1)
        b.movepiece(0,2)
        b.movepiece(1,2)
    elif b.height == 5: #31 moves
        b.movepiece(0,2)
        b.movepiece(0,1)
        b.movepiece(2,1)
        b.movepiece(0,2)
        b.movepiece(1,0)
        b.movepiece(1,2)
        b.movepiece(0,2)
        b.movepiece(0,1)
        b.movepiece(2,1)
        b.movepiece(2,0)
        b.movepiece(1,0)
        b.movepiece(2,1)
        b.movepiece(0,2)
        b.movepiece(0,1)
        b.movepiece(2,1)
        b.movepiece(0,2)
        b.movepiece(1,0)
        b.movepiece(1,2)
        b.movepiece(0,2)
        b.movepiece(1,0)
        b.movepiece(2,1)
        b.movepiece(2,0)
        b.movepiece(1,0)
        b.movepiece(1,2)
        b.movepiece(0,2)
        b.movepiece(0,1)
        b.movepiece(2,1)
        b.movepiece(0,2)
        b.movepiece(1,0)
        b.movepiece(1,2)
        b.movepiece(0,2)



b = GameBoard(3)
solve(b)
print(b.isComplete())
print(b.height, b.movesMade)
